name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # 1. 레포지토리 클론
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Flutter 설치
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4

      # 3. Flutter 의존성 설치
      - name: Install Dependencies
        run: flutter pub get

      # 4. Flutter Web 빌드
      - name: Build Flutter Web
        run: flutter build web --release

      # 5. Firebase Hosting 배포
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHEDULEMANAGEMENT_6F601 }}
          projectId: schedulemanagement-6f601
          channelId : live
